version: '2'

services:
  # MySQL Service
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - "3307:3306"
    networks:
      - bootApp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdb

  # Spring Boot Service
  bootApp:
    image: dockertest
    container_name: test
    ports:
      - "8080:8080"
    networks:
      - bootApp
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306

networks:
  bootApp:
    driver: bridge
