version: '2'

services:
  # MySQL Service
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - "3307:3306"  # Expose port 3307 on the host
    networks:
      - bootApp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdb

  # Spring Boot Service
  bootApp:
    image: dockertest
    container_name: test
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"  # Expose port 8080 on the host
    networks:
      - bootApp
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306  # MySQL default port

networks:
  bootApp:
    driver: bridge
